---
version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default: major

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/getsolus/solbuild)

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

linters:
  default: all
  disable:
    # Disabled to get codebase to pass the linter.
    # We can enable these one at a time.
    - cyclop
    - err113
    - errcheck
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gosec
    - lll
    - mnd
    - nestif
    - noctx
    - perfsprint
    - revive
    - wrapcheck
    # Disabled permanently
    - depguard        # manage using go.mod for now
    - exhaustruct     # structs may be uninitialized
    - funcorder       # functions are allowed in any order
    - nlreturn        # covered by wsl cuddle rules
    - noinlineerr     # inline errors are allowed for readability
    - nonamedreturns  # named returns are acceptable in short functions
    - paralleltest    # tests are acceptable in sequence
    # Deprecated
    - wsl
  exclusions:
    generated: lax
    rules:
      - linters:
          - err113
          - errcheck
          - gochecknoglobals
          - gosec
          - wrapcheck
        path: _test\.go
      - linters: [staticcheck]
        text: "ST1000:"
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    exhaustive:
      default-signifies-exhaustive: true

    govet:
      disable:
        - fieldalignment
      enable-all: true

    misspell:
      ignore-rules:
        - evolveos

    revive:
      enable-all-rules: false
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id

    staticcheck:
      checks:
        - all

    tagalign:
      order:
        - zero
        - short
        - long
        - desc

    varnamelen:
      min-name-length: 1
